# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ('hex_code',),
            },
        ),
    ]
