# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-30 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tagcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.AlterField(
            model_name='tagcolor',
            name='hex_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.TagColor'),
        ),
    ]
