# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-30 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181230_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main.Tag'),
        ),
    ]
