# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180128_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='stage',
            new_name='title',
        ),
    ]
