# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 02:10
from __future__ import unicode_literals
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180128_1950'),
    ]

    # this profile creation was not here before
    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='hex_code',
            field=models.CharField(blank=True, choices=[('#282C34', 'charleston'), ('#21252B', 'gunmetal'), ('#FF1053', 'light-red'), ('#FC7753', 'coral'), ('#5DA7E7', 'blue-jeans'), ('#00635D', 'rain-forest'), ('#A8ADBB', 'silver'), ('#08A4BD', 'blue-green'), ('#474b96', 'dark-blue'), ('#99c1a5', 'green'), ('#76c38d', 'sea-foam')], max_length=10),
        ),
    ]
