# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-01 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181230_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('label',)},
        ),
        migrations.AlterModelOptions(
            name='key',
            options={'ordering': ('label',)},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('label',)},
        ),
    ]
