# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171027_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='user',
            new_name='submitter',
        ),
        migrations.AlterField(
            model_name='track',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
