# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_hex_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='color',
            new_name='hex_code',
        ),
    ]
