# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180130_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('label',)},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='key',
            old_name='key',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='label',
        ),
    ]
