# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171027_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
