# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models.track


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171028_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='submitter',
            field=models.ForeignKey(default=main.models.track.get_superuser, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
