# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171029_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='projects',
            field=models.ManyToManyField(blank=True, to='main.Project'),
        ),
    ]
