# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171029_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stage',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='stage',
            new_name='status',
        ),
    ]
