# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20171029_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='projects',
            field=models.ManyToManyField(related_name='tracks', to='main.Project'),
        ),
    ]
