# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20171107_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=250, unique_for_date='pub_date'),
        ),
    ]
