# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20171109_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='date_recorded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
