# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20171109_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
