# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import main.models.track
import trakt.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20171109_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, default='', max_length=300, storage=trakt.storage.GoogleCloudStorage(), upload_to=main.models.track.format_storage_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='projects',
            field=models.ManyToManyField(blank=True, to='main.Project'),
        ),
    ]
