# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20171208_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='main.Project'),
        ),
    ]
