# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import main.models.track
import trakt.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_trackfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='audio_file',
        ),
        migrations.AlterField(
            model_name='trackfile',
            name='file',
            field=models.FileField(max_length=300, storage=trakt.storage.GoogleCloudStorage(), upload_to=main.models.track.format_file_storage_path),
        ),
    ]
