# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20171209_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackfile',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
