# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models.track
import trakt.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_trackfile_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(blank=True, max_length=300, storage=trakt.storage.GoogleCloudStorage(), upload_to=main.models.track.format_file_storage_path)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.Track')),
            ],
        ),
    ]
