# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_tracksession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='bpm',
            field=models.FloatField(),
        ),
    ]
