# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.template.defaultfilters import slugify
from django.db import migrations, models
from django.contrib.auth.models import User
import django.db.models.deletion

def update_users(apps, schema_editor):
    User = apps.get_model('django.contrib.auth', 'User')
    Profile = apps.get_model('main', 'Profile')
    for user in User.objects.all():
        slug = slugify(user.username + '_' + str(user.pk))
        profile = Profile.objects.create(user=user, cloud_slug=user.username)
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0030_auto_20171217_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('cloud_slug', models.SlugField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(update_users)
    ]
